//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_SOAP_REST_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public long ID { get; set; }
        public string SubCategorySymbol { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public double MinimumDensity { get; set; }
        public double MaximumDensity { get; set; }
        public string Units { get; set; }
        public string DocumentName { get; set; }
        public string AdditionalOption1 { get; set; }
        public string AdditionalOption2 { get; set; }
        public string AdditionalComments { get; set; }

        public static implicit operator MaterialWeight (Materials material)
        {
            var materialWeight = new MaterialWeight();

            materialWeight.MatWeightNo = (int)material.ID;
            materialWeight.MaterialName = material.Name;
            materialWeight.MinimumWeight = material.MinimumDensity;
            materialWeight.MaximumWeight = material.MaximumDensity;

            return materialWeight;
        }
    }
}
